sudo: required
language: python
python:
  - "3.6"      # current default Python on Travis CI

# command to run tests
addons:
  chrome: stable
#   firefox: "49.0"

# command to install dependencies
before_script:
  - echo $PATH
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser



install:

    - pip install -r requirements.txt

    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
script:
  - pytest


