sudo: required
language: python
python:
  - "3.6"      # current default Python on Travis CI

# command to run tests
addons:
  chrome: stable
#   firefox: "49.0"

# command to install dependencies
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
  - echo '$PATH'
  - wget https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7//bin/
  - export CHROME_BIN=chromium-browser

  - sleep 3


install:

    - pip install -r requirements.txt
script:
  - pytest


