sudo: required
language: python
python:
  - "3.6"      # current default Python on Travis CI

# command to run tests
addons:
  chrome: stable
#   firefox: "49.0"

# command to install dependencies
before_script:
  - echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
  - echo '$PATH'
  - wget http://chromedriver.storage.googleapis.com/71.0.3578.80/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7//bin/
  - export CHROME_BIN=chromium-browser



install:

    - pip install -r requirements.txt
script:
  - pytest


