version: '3.8'

networks:
    web:
      driver:  bridge

services:
  seleniumhub:
    image: selenium/hub
    ports:
      - 4444:4444


  chromenode:
    image: selenium/node-chrome-debug
    ports:
      - 33333:33333
    links:
      - seleniumhub:hub
    depends_on:
      - seleniumhub
    environment:
      HUB_HOST: seleniumhub


  firefoxnode:
    image: selenium/node-firefox-debug
    ports:
      - 33334:33334
    links:
      - seleniumhub:hub
    depends_on:
      - seleniumhub
    environment:
      HUB_HOST: seleniumhub


  jenkins:
    image: zasados/jenkins-python3.6
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - .:/var/jenkins_home


